
name: del

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:

    - name: 删除Actions运行记录
      uses: Mattraks/delete-workflow-runs@v2
      # if: steps.compile.outputs.status == 'success' && !cancelled()
      continue-on-error: true
      with:
          retain_days: 0     #保留最后多少记录不删除
          keep_minimum_runs: 0

    - name: 删除自动发布的旧固件
      uses: dev-drprasad/delete-older-releases@v0.3.3
      continue-on-error: true
      # if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
          keep_latest: 0     #保留多少个releases不删除
          delete_tags: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
