
name: del

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:

    - name: 微信通知
      uses: emon100/Action-Serverchan@v2

      with:
        SCKEY: ${{ secrets.SCKEY }}
        text: 主人${{matrix.target}}编译开始啦
        desp: 主人您要编译的[${{matrix.target}}]固件正在努力耕耘中(${{env.CangKu}}仓库的#${{env.Run_number}}号),请耐心等待......

    - name: 微信通知
      uses: emon100/Action-Serverchan@v2

      with:
        SCKEY: ${{ secrets.SCKEY }}
        text: 恭喜主人${{matrix.target}}固件编译成功！
        desp: 我亲爱的主人您使用${{matrix.target}}文件夹编译的[ ${{ env.CODE }}-${{ env.TARGET_PROFILE }} ]固件(${{ env.CangKu }}仓库的#${{ env.Run_number }}号)顺利编译完成了！
